"""update audio url

Revision ID: b2c149e1da03
Revises: 84064e78c200
Create Date: 2024-11-14 23:47:28.249608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2c149e1da03'
down_revision: Union[str, None] = '84064e78c200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('audio_url', sa.Text(), nullable=False))
    op.drop_column('pitches', 'audio_base64')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('audio_base64', mysql.TEXT(), nullable=False))
    op.drop_column('pitches', 'audio_url')
    # ### end Alembic commands ###
